### ISSUE TITLE
Please replace g++ with $(CXX) and gcc with $(CC) in the Makefile

### ISSUE THREAD

**Issue by yurivict** [tomszilagyi/ir.lv2#11]
Compiler can have different names on different platforms.

**Comment by yurivict** [comment]
https://github.com/tomszilagyi/ir.lv2/pull/12

**Comment by yurivict** [comment]
https://github.com/tomszilagyi/ir.lv2/pull/13

**Comment by tomszilagyi** [comment]
PRs merged
